sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - cache

env:
  global:
    secure: HqQihSflXXBGhNuYsUmi8mN3K6Wr5gfgOahzDjxjs5iJGyCr258BLJsEKh90PWIo8yykgW1hyGcBhxom7yjWo8HWyCjJANE0hCwRVGYV7emMwzRzsOAlDTwtjCJPTjEAZrXKQWLYeG+ZdVJqPx1vMdDoyHXW4rU3EZGv76uvHn8=

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - |
    set -o errexit
    case "${TRAVISOPERATION:-}" in
        codestyle)
            ;;
        *)
            sudo apt-get update -y || true
            sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
            sudo apt-get install -y ca-certificates libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev autoconf
            PHPUNIT_EXCLUDED_GROUPS_TMP=always-skipped
            if test "${IMAGINE_DRIVER:-}" = 'imagick' -o "${IMAGINE_DRIVER:-}" = 'all'; then ./.travis/imagick.sh; else PHPUNIT_EXCLUDED_GROUPS_TMP="${PHPUNIT_EXCLUDED_GROUPS_TMP},imagick"; fi
            if test "${IMAGINE_DRIVER:-}" = 'gmagick' -o "${IMAGINE_DRIVER:-}" = 'all'; then ./.travis/gmagick.sh; else PHPUNIT_EXCLUDED_GROUPS_TMP="${PHPUNIT_EXCLUDED_GROUPS_TMP},gmagick"; fi
            if test -z "${PHPUNIT_EXCLUDED_GROUPS:-}"; then PHPUNIT_EXCLUDED_GROUPS="$PHPUNIT_EXCLUDED_GROUPS_TMP"; fi
            php --ri gd || true
            composer --no-interaction remove --dev --no-update --no-scripts friendsofphp/php-cs-fixer
            ;;
    esac
  - php --ri curl || true
  - ifconfig || true
  - composer --no-interaction install
  - set +o errexit

script:
  - |
    set -o errexit
    case "${TRAVISOPERATION:-}" in
        codestyle)
            composer --no-interaction codestyle -- --no-interaction --dry-run --diff -- .
            ;;
        *)
            composer --no-interaction test -- --exclude-group="${PHPUNIT_EXCLUDED_GROUPS}" ${PHPUNIT_EXTRA_FLAGS:-}
            ;;
    esac
    set +o errexit
  - if test -n "${AUTOUPDATE_API:-}"; then ./.travis/autoupdate-api.sh; fi

matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly (all drivers)
  include:
    -
      name: Test with PHP 7.3 (all drivers)
      php: '7.3'
      env:
        - IMAGINE_DRIVER: all
    -
      name: Test with PHP 7.3 (gmagick driver, ondrej/php PPA)
      php: '7.2'
      env:
        - IMAGINE_DRIVER: gmagick
        - GRAPHICSMAGIC_VERSION: ondrej
        - PHPUNIT_EXCLUDED_GROUPS: none
        - PHPUNIT_EXTRA_FLAGS: --filter=OndrejImageTest::testSaveWithoutFileExtension
